"""Incident report builders (JSON and Markdown)."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from .cases import create_cases_from_alerts, summarize_cases
from .correlation import correlate_findings
from .coverage import build_detection_coverage_matrix, summarize_coverage
from .entities import build_entity_profiles, summarize_entities
from .false_positive import (
    annotate_alerts_with_fp_likelihood,
    summarize_false_positive_review,
)
from .kill_chain import build_kill_chain_view
from .mitre import enrich_findings_with_mitre
from .risk import score_finding, score_incident, severity_from_score, sort_findings_by_severity
from .schemas import Finding, IncidentReport, ParsedEvent
from .summarizer import summarize_findings
from .timeline import build_timeline
from .triage import generate_alerts_from_findings, summarize_alert_queue


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_incident_report(
    findings: List[Finding], total_events: int
) -> IncidentReport:
    enrich_findings_with_mitre(findings)
    for f in findings:
        score_finding(f)
    sorted_findings = sort_findings_by_severity(findings)
    overall_score = score_incident(sorted_findings)
    return IncidentReport(
        generated_at=_utc_now_iso(),
        total_events=total_events,
        total_findings=len(sorted_findings),
        overall_score=overall_score,
        overall_severity=severity_from_score(overall_score),
        findings=sorted_findings,
        timeline=build_timeline(sorted_findings),
        correlated_incidents=correlate_findings(sorted_findings),
        ai_summary=summarize_findings(sorted_findings),
    )


def build_markdown_report(report: IncidentReport) -> str:
    lines: List[str] = []
    lines.append("# Security Incident Report")
    lines.append("")
    lines.append(f"- Generated: {report.generated_at}")
    lines.append(f"- Total events parsed: {report.total_events}")
    lines.append(f"- Total findings: {report.total_findings}")
    lines.append(
        f"- Overall risk score: {report.overall_score} ({report.overall_severity})"
    )
    lines.append("")
    lines.append("## AI Summary (local mock)")
    lines.append("")
    lines.append(report.ai_summary)
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    for f in report.findings:
        lines.append(
            f"### [{f.severity.upper()}] {f.rule_id} - {f.rule_name} (score {f.score})"
        )
        lines.append("")
        lines.append(f"- Description: {f.description}")
        if f.mitre_techniques:
            lines.append(
                "- MITRE ATT&CK: " + ", ".join(f.mitre_techniques)
            )
        lines.append(f"- Matched events: {len(f.matched_events)}")
        for ev in f.matched_events[:5]:
            lines.append(f"  - `{ev.raw}`")
        lines.append("")
    lines.append("## Timeline")
    lines.append("")
    for entry in report.timeline:
        lines.append(
            f"- {entry.timestamp} | [{entry.severity}] {entry.rule_id} {entry.summary}"
        )
    lines.append("")
    lines.append("## Correlated Incidents")
    lines.append("")
    for inc in report.correlated_incidents:
        lines.append(
            f"- {inc.incident_id} actor={inc.actor} score={inc.score} rules={','.join(inc.rule_ids)}"
        )
    lines.append("")
    lines.append(
        "_AI-assisted disclosure: this report was generated by a local "
        "rule-based engine. No external LLM was contacted._"
    )
    return "\n".join(lines)


def build_soc_report(
    events: List[ParsedEvent],
    findings: List[Finding],
) -> Dict[str, Any]:
    """Build the SOC report payload (v2).

    Includes: executive summary, alert queue, cases, entities, MITRE
    coverage, kill chain, timeline, findings, recommendations, FP notes,
    limitations.
    """
    enrich_findings_with_mitre(findings)
    for f in findings:
        score_finding(f)
    findings = sort_findings_by_severity(findings)

    overall = score_incident(findings)
    severity = severity_from_score(overall)
    correlated = correlate_findings(findings)
    timeline = build_timeline(findings)

    alerts = generate_alerts_from_findings(findings)
    annotate_alerts_with_fp_likelihood(alerts)
    queue_summary = summarize_alert_queue(alerts)
    fp_summary = summarize_false_positive_review(alerts)

    cases = create_cases_from_alerts(alerts, correlated)
    case_summary = summarize_cases(cases)

    entities = build_entity_profiles(events, findings, alerts)
    entity_summary = summarize_entities(entities)

    coverage_matrix = build_detection_coverage_matrix()
    coverage_summary = summarize_coverage(coverage_matrix)

    kill_chain = build_kill_chain_view(findings, correlated)

    recommendations: List[str] = []
    for c in cases:
        recommendations.extend(c.recommended_actions)
    # Deduplicate while preserving order.
    seen: set = set()
    recommendations = [r for r in recommendations if not (r in seen or seen.add(r))]

    exec_summary = (
        f"Across {len(events)} parsed event(s), the platform produced "
        f"{len(findings)} finding(s), {len(alerts)} alert(s), and "
        f"{len(cases)} case(s). Overall risk score is {overall} ({severity}). "
        f"Highest reached kill-chain stage: {kill_chain.highest_stage or 'none'}. "
        f"MITRE coverage rate: {coverage_summary['coverage_rate']:.0%}."
    )

    return {
        "generated_at": _utc_now_iso(),
        "executive_summary": exec_summary,
        "overall_score": overall,
        "overall_severity": severity,
        "total_events": len(events),
        "total_findings": len(findings),
        "alerts": [a.model_dump() for a in alerts],
        "queue_summary": queue_summary,
        "cases": [c.model_dump() for c in cases],
        "case_summary": case_summary,
        "entities": [e.model_dump() for e in entities],
        "entity_summary": entity_summary,
        "coverage_matrix": [e.model_dump() for e in coverage_matrix],
        "coverage_summary": coverage_summary,
        "kill_chain": kill_chain.model_dump(),
        "timeline": [t.model_dump() for t in timeline],
        "findings": [f.model_dump() for f in findings],
        "correlated_incidents": [c.model_dump() for c in correlated],
        "false_positive_summary": fp_summary,
        "recommendations": recommendations,
        "limitations": [
            "Mock AI summarizer; no external LLM was contacted.",
            "All sample IPs are RFC 5737 test ranges or RFC 1918 private addresses.",
            "No persistence layer; analyses run in-memory per request.",
            "Detection rules are intentionally simple for demonstration purposes.",
        ],
        "ai_disclosure": (
            "This report was produced by a local AI-assisted platform. The "
            "architecture, detection scenarios, and review process were "
            "directed by the author. No external LLM service was contacted."
        ),
    }


def build_soc_markdown_report(soc_report: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("# SOC Analyst Report")
    lines.append("")
    lines.append(f"- Generated: {soc_report['generated_at']}")
    lines.append(
        f"- Overall risk: {soc_report['overall_score']} ({soc_report['overall_severity']})"
    )
    lines.append(f"- Events: {soc_report['total_events']}")
    lines.append(f"- Findings: {soc_report['total_findings']}")
    lines.append(f"- Alerts: {len(soc_report['alerts'])}")
    lines.append(f"- Cases: {len(soc_report['cases'])}")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(soc_report["executive_summary"])
    lines.append("")

    lines.append("## Alert Queue Summary")
    lines.append("")
    qs = soc_report["queue_summary"]
    lines.append(f"- Total alerts: {qs['total_alerts']}")
    lines.append(f"- Open alerts: {qs['open_alerts']}")
    lines.append(f"- Priority: {qs['priority_counts']}")
    lines.append(f"- Severity: {qs['severity_counts']}")
    lines.append("")

    lines.append("## Incident Cases")
    lines.append("")
    for c in soc_report["cases"]:
        lines.append(
            f"### {c['case_id']} - {c['title']} [{c['severity'].upper()} / {c['priority']}]"
        )
        lines.append(f"- Type: {c['case_type']}")
        lines.append(f"- Source IPs: {', '.join(c['src_ips']) or 'n/a'}")
        lines.append(
            f"- MITRE: {', '.join(c['mitre_techniques']) or 'n/a'}"
        )
        lines.append(f"- Summary: {c['summary']}")
        if c["recommended_actions"]:
            lines.append("- Recommended actions:")
            for r in c["recommended_actions"]:
                lines.append(f"  - {r}")
        lines.append("")

    lines.append("## Entity Risk Profiles")
    lines.append("")
    for e in soc_report["entities"][:10]:
        lines.append(
            f"- {e['entity_type']}:{e['entity_id']} score={e['risk_score']} "
            f"sev={e['severity']} findings={e['finding_count']} alerts={e['alert_count']}"
        )
    lines.append("")

    lines.append("## MITRE Coverage")
    lines.append("")
    cs = soc_report["coverage_summary"]
    lines.append(
        f"- Coverage rate: {cs['coverage_rate']:.0%} "
        f"({cs['covered']}/{cs['total_techniques']})"
    )
    for e in soc_report["coverage_matrix"]:
        lines.append(
            f"- {e['technique_id']} {e['technique_name']} ({e['tactic']}) "
            f"-> {'covered' if e['covered'] else 'uncovered'} [{e['coverage_strength']}]"
        )
    lines.append("")

    lines.append("## Kill Chain View")
    lines.append("")
    kc = soc_report["kill_chain"]
    lines.append(kc["narrative"])
    for st in kc["stages"]:
        marker = "X" if st["observed"] else " "
        lines.append(
            f"- [{marker}] {st['stage']} (findings={st['finding_count']}, "
            f"techniques={', '.join(st['mitre_techniques']) or '-'})"
        )
    lines.append("")

    lines.append("## Timeline")
    lines.append("")
    for t in soc_report["timeline"][:50]:
        lines.append(
            f"- {t['timestamp']} | [{t['severity']}] {t['rule_id']} {t['summary']}"
        )
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    for f in soc_report["findings"]:
        lines.append(
            f"- [{f['severity'].upper()}] {f['rule_id']} {f['rule_name']} "
            f"(events={len(f['matched_events'])}, score={f['score']})"
        )
    lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    for r in soc_report["recommendations"]:
        lines.append(f"- {r}")
    lines.append("")

    lines.append("## False Positive Notes")
    lines.append("")
    fp = soc_report["false_positive_summary"]
    lines.append(
        f"- low={fp['low_likelihood']}, medium={fp['medium_likelihood']}, "
        f"high={fp['high_likelihood']}"
    )
    for item in fp["review_recommended"]:
        lines.append(
            f"  - {item['alert_id']} {item['title']} ({item['likelihood']} likelihood)"
        )
    lines.append("")

    lines.append("## Limitations")
    lines.append("")
    for lim in soc_report["limitations"]:
        lines.append(f"- {lim}")
    lines.append("")

    lines.append(f"_{soc_report['ai_disclosure']}_")
    return "\n".join(lines)


# --- v3 reports ---


def build_executive_report(events: List[ParsedEvent], findings: List[Finding]) -> str:
    """Executive-style Markdown report. Business-tone, less technical detail."""
    from .playbooks import recommend_playbooks

    soc = build_soc_report(events, findings)
    top_cases = [c for c in soc["cases"] if c["severity"] in ("critical", "high")]
    high_entities = [e for e in soc["entities"] if e["severity"] in ("critical", "high")]
    playbook_recs = recommend_playbooks(findings)

    lines: List[str] = []
    lines.append("# Executive Security Report")
    lines.append("")
    lines.append(f"- Generated: {soc['generated_at']}")
    lines.append(f"- Overall risk: {soc['overall_score']}/100 ({soc['overall_severity']})")
    lines.append(f"- Events analyzed: {soc['total_events']}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(soc["executive_summary"])
    lines.append("")
    lines.append("## Top Risks")
    lines.append("")
    if top_cases:
        for c in top_cases:
            lines.append(
                f"- {c['title']} (case {c['case_id']}, severity {c['severity']})"
            )
    else:
        lines.append("- No high or critical cases at this time.")
    lines.append("")
    lines.append("## Business Impact")
    lines.append("")
    if high_entities:
        lines.append(
            f"- {len(high_entities)} entity(ies) flagged as high or critical risk."
        )
        lines.append(
            f"- Highest risk score observed: {high_entities[0]['risk_score']}."
        )
    else:
        lines.append("- No high-risk entities observed in this window.")
    lines.append(
        f"- Detection coverage of MITRE ATT&CK: {soc['coverage_summary']['coverage_rate']:.0%}."
    )
    lines.append("")
    lines.append("## High-Priority Cases")
    lines.append("")
    if top_cases:
        for c in top_cases:
            lines.append(
                f"- {c['case_id']}: {c['title']} -> priority {c['priority']}, "
                f"{len(c['related_alert_ids'])} alert(s)."
            )
    else:
        lines.append("- None.")
    lines.append("")
    lines.append("## Recommended Executive Actions")
    lines.append("")
    if playbook_recs:
        for pb in playbook_recs:
            lines.append(f"- Approve and resource playbook: {pb['title']}.")
    if soc["recommendations"]:
        for r in soc["recommendations"][:5]:
            lines.append(f"- {r}")
    if not playbook_recs and not soc["recommendations"]:
        lines.append("- Continue monitoring; no immediate action required.")
    lines.append("")
    lines.append("## Limitations")
    lines.append("")
    for lim in soc["limitations"]:
        lines.append(f"- {lim}")
    lines.append(
        "- This is a local educational report based on synthetic data."
    )
    lines.append("")
    lines.append(f"_{soc['ai_disclosure']}_")
    return "\n".join(lines)


def build_analyst_report(events: List[ParsedEvent], findings: List[Finding]) -> str:
    """SOC-analyst-focused Markdown report."""
    from .playbooks import recommend_playbooks

    soc = build_soc_report(events, findings)
    playbook_recs = recommend_playbooks(findings)

    lines: List[str] = []
    lines.append("# SOC Analyst Investigation Report")
    lines.append("")
    lines.append(f"- Generated: {soc['generated_at']}")
    lines.append(
        f"- Overall risk: {soc['overall_score']}/100 ({soc['overall_severity']})"
    )
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    for f in soc["findings"]:
        lines.append(
            f"- [{f['severity'].upper()}] {f['rule_id']} {f['rule_name']} "
            f"(events={len(f['matched_events'])}, score={f['score']})"
        )
    lines.append("")
    lines.append("## Evidence")
    lines.append("")
    for f in soc["findings"][:8]:
        for ev in f["matched_events"][:3]:
            lines.append(f"- `{ev['raw']}`")
    lines.append("")
    lines.append("## Timeline")
    lines.append("")
    for t in soc["timeline"][:30]:
        lines.append(
            f"- {t['timestamp']} | [{t['severity']}] {t['rule_id']} {t['summary']}"
        )
    lines.append("")
    lines.append("## Cases")
    lines.append("")
    for c in soc["cases"]:
        lines.append(
            f"- {c['case_id']} {c['title']} (sev {c['severity']}, "
            f"{len(c['related_alert_ids'])} alerts)"
        )
    lines.append("")
    lines.append("## Entities")
    lines.append("")
    for e in soc["entities"][:10]:
        lines.append(
            f"- {e['entity_type']}:{e['entity_id']} score={e['risk_score']} "
            f"sev={e['severity']}"
        )
    lines.append("")
    lines.append("## MITRE ATT&CK")
    lines.append("")
    for e in soc["coverage_matrix"]:
        if e["covered"]:
            lines.append(
                f"- {e['technique_id']} {e['technique_name']} via "
                f"{', '.join(e['rule_ids'])}"
            )
    lines.append("")
    lines.append("## Playbooks")
    lines.append("")
    if playbook_recs:
        for pb in playbook_recs:
            lines.append(
                f"- {pb['id']} {pb['title']} (sev {pb['severity']})"
            )
    else:
        lines.append("- No playbooks matched.")
    lines.append("")
    lines.append("## Triage Steps")
    lines.append("")
    for r in soc["recommendations"]:
        lines.append(f"- {r}")
    lines.append("")
    lines.append("_Local educational report; no external services contacted._")
    return "\n".join(lines)


def build_detection_engineering_report_markdown(report: Dict) -> str:
    """Detection-engineer-focused Markdown rendering."""
    lines: List[str] = []
    lines.append("# Detection Engineering Report")
    lines.append("")
    lines.append(f"- Generated: {report['generated_at']}")
    lines.append(f"- Rules: {report['rule_count']}")
    lines.append(
        f"- Average quality score: {report['average_quality_score']}"
    )
    lines.append(
        f"- Quality distribution: {report['quality_distribution']}"
    )
    lines.append("")
    lines.append("## Rule Quality")
    lines.append("")
    for q in report["rule_quality"]:
        lines.append(
            f"### {q['rule_id']} - {q['quality_level']} ({q['quality_score']}/100)"
        )
        if q["strengths"]:
            lines.append("- Strengths:")
            for s in q["strengths"]:
                lines.append(f"  - {s}")
        if q["weaknesses"]:
            lines.append("- Weaknesses:")
            for w in q["weaknesses"]:
                lines.append(f"  - {w}")
        if q["improvement_suggestions"]:
            lines.append("- Suggestions:")
            for s in q["improvement_suggestions"]:
                lines.append(f"  - {s}")
        lines.append("")
    lines.append("## Detection Coverage")
    lines.append("")
    cs = report["coverage_summary"]
    lines.append(
        f"- Coverage rate: {cs['coverage_rate']:.0%} "
        f"({cs['covered']}/{cs['total_techniques']})"
    )
    lines.append("")
    lines.append("## Evaluation Metrics")
    lines.append("")
    m = report["evaluation_metrics"]
    lines.append(
        f"- TP={m['true_positives']}, FP={m['false_positives']}, "
        f"FN={m['false_negatives']}"
    )
    lines.append(
        f"- Precision={m['precision']:.3f}, recall={m['recall']:.3f}, "
        f"F1={m['f1_score']:.3f}"
    )
    lines.append("")
    lines.append("## False Positive Notes")
    lines.append("")
    for rm in report["rule_metrics"]:
        if rm["false_positives"] > 0:
            lines.append(
                f"- {rm['rule_id']} has {rm['false_positives']} FP(s) across scenarios."
            )
    if not any(rm["false_positives"] for rm in report["rule_metrics"]):
        lines.append("- No false positives observed across evaluation scenarios.")
    lines.append("")
    lines.append("## Rule Tuning Suggestions")
    lines.append("")
    for rec in report["tuning_recommendations"]:
        lines.append(
            f"- {rec['rule_id']} [{rec['recommendation_type']}]: "
            f"{rec['suggested_change']}"
        )
    if not report["tuning_recommendations"]:
        lines.append("- No tuning recommendations at this time.")
    lines.append("")
    lines.append("## Detection Gaps")
    lines.append("")
    gaps = report["coverage_gaps"]
    if gaps["uncovered_techniques"]:
        lines.append(
            f"- Uncovered MITRE techniques: {', '.join(gaps['uncovered_techniques'])}"
        )
    if gaps["weakly_covered_techniques"]:
        lines.append(
            f"- Weakly covered MITRE techniques: {', '.join(gaps['weakly_covered_techniques'])}"
        )
    for sg in gaps["scenario_gaps"]:
        lines.append(
            f"- Scenario {sg['scenario_id']} missing rules: {', '.join(sg['missing_rule_ids'])}"
        )
    if (
        not gaps["uncovered_techniques"]
        and not gaps["weakly_covered_techniques"]
        and not gaps["scenario_gaps"]
    ):
        lines.append("- No coverage or scenario gaps detected.")
    lines.append("")
    lines.append(f"_{report['ai_disclosure']}_")
    return "\n".join(lines)
