"""Incident report builders (JSON and Markdown)."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from .correlation import correlate_findings
from .mitre import enrich_findings_with_mitre
from .risk import score_finding, score_incident, severity_from_score, sort_findings_by_severity
from .schemas import Finding, IncidentReport
from .summarizer import summarize_findings
from .timeline import build_timeline


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_incident_report(
    findings: List[Finding], total_events: int
) -> IncidentReport:
    enrich_findings_with_mitre(findings)
    for f in findings:
        score_finding(f)
    sorted_findings = sort_findings_by_severity(findings)
    overall_score = score_incident(sorted_findings)
    return IncidentReport(
        generated_at=_utc_now_iso(),
        total_events=total_events,
        total_findings=len(sorted_findings),
        overall_score=overall_score,
        overall_severity=severity_from_score(overall_score),
        findings=sorted_findings,
        timeline=build_timeline(sorted_findings),
        correlated_incidents=correlate_findings(sorted_findings),
        ai_summary=summarize_findings(sorted_findings),
    )


def build_markdown_report(report: IncidentReport) -> str:
    lines: List[str] = []
    lines.append("# Security Incident Report")
    lines.append("")
    lines.append(f"- Generated: {report.generated_at}")
    lines.append(f"- Total events parsed: {report.total_events}")
    lines.append(f"- Total findings: {report.total_findings}")
    lines.append(
        f"- Overall risk score: {report.overall_score} ({report.overall_severity})"
    )
    lines.append("")
    lines.append("## AI Summary (local mock)")
    lines.append("")
    lines.append(report.ai_summary)
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    for f in report.findings:
        lines.append(
            f"### [{f.severity.upper()}] {f.rule_id} - {f.rule_name} (score {f.score})"
        )
        lines.append("")
        lines.append(f"- Description: {f.description}")
        if f.mitre_techniques:
            lines.append(
                "- MITRE ATT&CK: " + ", ".join(f.mitre_techniques)
            )
        lines.append(f"- Matched events: {len(f.matched_events)}")
        for ev in f.matched_events[:5]:
            lines.append(f"  - `{ev.raw}`")
        lines.append("")
    lines.append("## Timeline")
    lines.append("")
    for entry in report.timeline:
        lines.append(
            f"- {entry.timestamp} | [{entry.severity}] {entry.rule_id} {entry.summary}"
        )
    lines.append("")
    lines.append("## Correlated Incidents")
    lines.append("")
    for inc in report.correlated_incidents:
        lines.append(
            f"- {inc.incident_id} actor={inc.actor} score={inc.score} rules={','.join(inc.rule_ids)}"
        )
    lines.append("")
    lines.append(
        "_AI-assisted disclosure: this report was generated by a local "
        "rule-based engine. No external LLM was contacted._"
    )
    return "\n".join(lines)
